### ISSUE TITLE
Configure and implement Pytest

### ISSUE THREAD

**Issue by arthurTemporim** [ralphg6/david#68]
This issue aims to configure a unit tests tool.

Tasks:

- [x] Define a test tool (probably pytest)
- [x] Configure it locally
- [x] Add tests to CI
- [x] Add badge of project coverage
- [x] Create the first test of the project

Is important too:

- [x] Define how to make **integration** tests (very important to `components` usage). Moved to #76 
- [x] ~~Define how to make **stress** tests~~
- [x] Define how to make **load** tests. Moved to #77

**Comment by arthurTemporim** [comment]
After a quick search I guess the best testing tool is [pytest](https://docs.pytest.org/en/latest/)
This was the source that I used: [PythonTestingToolsTaxonomy](https://wiki.python.org/moin/PythonTestingToolsTaxonomy)

**Comment by arthurTemporim** [comment]
The `pytest` organization of this project followed this tutorial:
[Good Practices](https://docs.pytest.org/en/latest/goodpractices.html)

**Comment by arthurTemporim** [comment]
To add the test coverage badge to this project is needed an action by the owner @ralphg6.
This project README has the needed steps [codecov](https://github.com/codecov/example-python#can-i-upload-my-coverage-files)

1. Access codecov site and create an account (I made it using my GitHub account) [codecov site](https://codecov.io)
2. Agree with codecov terms
3. Add `David` project to codecov list
4. Use the generated token to link the badge
5. Add the codecov link to README

I suggest to first make this configuration in test `branch` and after everything works move it to `develop` and `master`.

**Comment by arthurTemporim** [comment]
Another option is to use this simple and awesome project to generate the badge image:
[coverage-badge](https://github.com/dbrgn/coverage-badge)

After that is just needed to store the badge somewhere in the repository and link it to README.md, some more configurations must be needed in CI tools.

What do you think? :thinking:

**Comment by ralphg6** [comment]
[![codecov](https://codecov.io/gh/ralphg6/david/branch/develop/graph/badge.svg)](https://codecov.io/gh/ralphg6/david)
```md
[![codecov](https://codecov.io/gh/ralphg6/david/branch/develop/graph/badge.svg)](https://codecov.io/gh/ralphg6/david)
```

**Comment by ralphg6** [comment]
I removed codecov integration why Codeclimate already is configurated and he to integrate with the Coverage.py and the integration already was configured.

@arthurTemporim for me, the task 'Add badge of project coverage' was completed by #74.
