### ISSUE TITLE
Add codeclimate badge

### ISSUE THREAD

**Issue by arthurTemporim** [ralphg6/david#74]
To show how technically good is this project, add the [codeclimate](https://codeclimate.com/) is needed.

@ralphg6 as owner to add it is needed:

1. Sign up into `codeclimate` (using GitHub account if you want)
2. Add `David` project to codeclimate
3. After the build, just click in `Repo Settings` and copy the badge URL

Now the project is classified as `A` it is the best rank of codeclimate! congratulations!!
I updated my fork with this badge if you want to see it:
https://github.com/arthurTemporim/david

**Comment by arthurTemporim** [comment]
Codeclimate can show test coverage too, this can be other option to #68

**Comment by ralphg6** [comment]
[![Maintainability](https://api.codeclimate.com/v1/badges/2eb8ba0d056e3b52f34a/maintainability)](https://codeclimate.com/github/ralphg6/david/maintainability)
```md
[![Maintainability](https://api.codeclimate.com/v1/badges/2eb8ba0d056e3b52f34a/maintainability)](https://codeclimate.com/github/ralphg6/david/maintainability)]
```

[![Test Coverage](https://api.codeclimate.com/v1/badges/2eb8ba0d056e3b52f34a/test_coverage)](https://codeclimate.com/github/ralphg6/david/test_coverage)
```md
[![Test Coverage](https://api.codeclimate.com/v1/badges/2eb8ba0d056e3b52f34a/test_coverage)](https://codeclimate.com/github/ralphg6/david/test_coverage)
```

**Comment by ralphg6** [comment]
The Github Actions was configured to send coverage report to Codeclimate and [Coverage.py](https://coverage.readthedocs.io/en/coverage-5.0.3/index.html) too.
