### ISSUE TITLE
Improve code documentation

### ISSUE THREAD

**Issue by ralphg6** [ralphg6/david#8]
To improve code maintainability and make the project learning curve easier, code documentation should be configurated and described.

**Comment by arthurTemporim** [comment]
I followed this tutorial to configure `sphinx` to code documentation:

[sphinx tutorial](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/read-the-docs.html)

After all steps, the documentation was published here:
[david documentation](https://david-ausubel.readthedocs.io/en/latest/?badge=latest#)

**Comment by arthurTemporim** [comment]
After the PR #32 is closed is needed to add the `docstring` documentation to each python module, but this will be a continuous process. And this documentation will be useful for it:
[docstrings](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html)
