### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by ralphg6** [ralphg6/david#9]
The README.md is the face of the project, so relevant information and descriptions is important to engage community members to **use** and **contribute** to this project. This `issue` aims to improve this project README.md.

**Comment by arthurTemporim** [comment]
This project have a good `README.md` template:
[README template](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)

**Comment by arthurTemporim** [comment]
The project README was updated following the README template from the previous comment :D

**Comment by ralphg6** [comment]
> This project have a good `README.md` template:
> [README template](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)

I saw this example and i was going suggest but forgot.
